---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Project

<!-- badges: start -->
<!-- badges: end -->

The goal of Project is to make predictions as to whether a person is going to recomend or not recommend based off of their review of an airline trip. This project contains four main folders, as detailed below. 

## R/ 

This is where our code is located. A quick overview of the scripts is as follows: 

*  **app.R** : Code for the associated RShiny App.
* **attributes_model.R** : Code for checking which non-text attributes were good predictors. Done with logistic regression. 
* **matrix_text_processing.R**: Turning the reviews of our data set into a functional Document-Term Matrix. 
* **train_lr_glmnet.R**: Training and testing the Logistic Regression model. 
* **train_nb.R**: Training and testing the Naive Bayes model. 
* **train_svm.R**: Training adn testing the Support Vector Machine model. 
* **train_rf.R**: Training the Random Forest model. 

### rds/

This is where our data is saved. Many of the datasets were taking too long to load as csv files (i.e 10 minutes), so we chose to save our data in RDS form instead. Here we saved the resuls of our training models, training and testing IDs (for accuracy of model comparison on the cluster) and different DTM matrices. 


### Cluster_Output/ 

Contains the results from all the training scripts in **R/** after they were run on the cluster. 

### report/ 

The folder containg our final report in .Rmd format for this project (See this for more details on the project)

## Group Members 
* **Tahmeed Tureen** *(tureen@umich.edu)*
* **Mandy Meng Ni Ho** *(mandyho@umich.edu)*
* **Ben Brennan** *(brennben@umich.edu)*

Thanks for checking out our project. :) 


